

export const initialNodes = [
  { id: '1', type: 'custom', hidden: false, expanded: true, data: { nodeId: '1', label: 'Node 1', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '2', type: 'custom', expanded: true, data: { nodeId: '2', label: 'Node 2', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '3', type: 'custom', expanded: true, data: { nodeId: '3', label: 'Node 3', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '4', type: 'custom', expanded: true, data: { nodeId: '4', label: 'Node 4', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '5', type: 'custom', expanded: true, data: { nodeId: '5', label: 'Node 5', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '6', type: 'custom', expanded: true, data: { nodeId: '6', label: 'Node 6', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '7', type: 'custom', expanded: true, data: { nodeId: '7', label: 'Node 7', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '8', type: 'custom', expanded: true, data: { nodeId: '8', label: 'Node 8', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '9', type: 'custom', expanded: true, data: { nodeId: '9', label: 'Node 9', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '10', type: 'custom', expanded: true, data: { nodeId: '10', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '11', type: 'custom', expanded: true, data: { nodeId: '11', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '12', type: 'custom', expanded: true, data: { nodeId: '12', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '13', type: 'custom', expanded: true, data: { nodeId: '13', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '14', type: 'custom', expanded: true, data: { nodeId: '14', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '15', type: 'custom', expanded: true, data: { nodeId: '15', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '16', type: 'custom', expanded: true, data: { nodeId: '16', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '17', type: 'custom', expanded: true, data: { nodeId: '17', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '18', type: 'custom', expanded: true, data: { nodeId: '18', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '19', type: 'custom', expanded: true, data: { nodeId: '19', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '20', type: 'custom', expanded: true, data: { nodeId: '20', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '21', type: 'custom', expanded: true, data: { nodeId: '21', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '22', type: 'custom', expanded: true, data: { nodeId: '22', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '23', type: 'custom', expanded: true, data: { nodeId: '23', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '24', type: 'custom', expanded: true, data: { nodeId: '24', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '25', type: 'custom', expanded: true, data: { nodeId: '25', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '26', type: 'custom', expanded: true, data: { nodeId: '26', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '27', type: 'custom', expanded: true, data: { nodeId: '27', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '28', type: 'custom', expanded: true, data: { nodeId: '28', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '29', type: 'custom', expanded: true, data: { nodeId: '29', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '30', type: 'custom', expanded: true, data: { nodeId: '30', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },
  { id: '31', type: 'custom', expanded: true, data: { nodeId: '31', label: 'Node 10', showBackground: false }, position: { x: 0, y: 0 } },

];

export const initialEdges = [
  { id: 'e1-2', source: '1', target: '2', type: 'default' },
  { id: 'e1-3', source: '1', target: '3', type: 'default' },
  { id: 'e2-4', source: '2', target: '4', type: 'default' },
  { id: 'e2-5', source: '2', target: '5', type: 'default' },
  { id: 'e3-6', source: '3', target: '6', type: 'default' },
  { id: 'e3-7', source: '3', target: '7', type: 'default' },
  { id: 'e3-5', source: '3', target: '5', type: 'default' },
  { id: 'e4-8', source: '4', target: '8', type: 'default' },
  { id: 'e4-9', source: '4', target: '9', type: 'default' },
  { id: 'e5-10', source: '5', target: '10', type: 'default' },
  { id: 'e5-11', source: '5', target: '11', type: 'default' },
  { id: 'e6-12', source: '6', target: '12', type: 'default' },
  { id: 'e6-13', source: '6', target: '13', type: 'default' },
  { id: 'e7-14', source: '7', target: '14', type: 'default' },
  { id: 'e7-15', source: '7', target: '15', type: 'default' },
  { id: 'e8-16', source: '8', target: '16', type: 'default' },
  { id: 'e8-17', source: '8', target: '17', type: 'default' },
  { id: 'e9-18', source: '9', target: '18', type: 'default' },
  { id: 'e9-19', source: '9', target: '19', type: 'default' },
  { id: 'e10-20', source: '10', target: '20', type: 'default' },
  { id: 'e10-21', source: '10', target: '21', type: 'default' },
  { id: 'e11-22', source: '11', target: '22', type: 'default' },
  { id: 'e11-23', source: '11', target: '23', type: 'default' },
  { id: 'e12-24', source: '12', target: '24', type: 'default' },
  { id: 'e12-25', source: '12', target: '25', type: 'default' },
  { id: 'e13-26', source: '13', target: '26', type: 'default' },
  { id: 'e13-27', source: '13', target: '27', type: 'default' },
  { id: 'e14-28', source: '14', target: '28', type: 'default' },
  { id: 'e14-29', source: '14', target: '29', type: 'default' },
  { id: 'e15-30', source: '15', target: '30', type: 'default' },
  { id: 'e15-31', source: '15', target: '31', type: 'default' },

];
